server:
  port: 9193

spring:
  datasource:
    username: root
    password: motdepasse123
    url: jdbc:mysql://localhost:3306/student_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true